# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
    - DJANGO="Django==1.7"
    - DJANGO="Django==1.8"
    - DJANGO="Django==1.9rc2"


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install $DJANGO
 - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source staticgen runtests.py

# report coverage to coveralls.io
after_success: coveralls
